spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    #показывать все sql запросы
    properties:
      hibernate:
        format_sql: true